Always build shared lib on Windows
I saw the following link errors on Windows:

$ zig build sample
sample
└─ run exe sample
   └─ compile exe sample Debug native failure
error: warning(link): unexpected LLD stderr:
lld-link: warning: .zig-cache\o\a0f3dd89353c48f8c5a4259f396cceea\bm.obj: locally defined symbol imported: benchmark::internal::InitializeStreams() (defined in benchmark.lib(benchmark.obj)) [LNK4217]
lld-link: warning: .zig-cache\o\a0f3dd89353c48f8c5a4259f396cceea\bm.obj: locally defined symbol imported: benchmark::internal::RegisterBenchmarkInternal(std::__1::unique_ptr<benchmark::Benchmark, std::__1::default_delete<benchmark::Benchmark>>) (defined in benchmark.lib(benchmark_register.obj)) [LNK4217]
...

Setting BENCHMARK_STATIC_DEFINE for all targets, including the final
benchmark executable, fixes this but that would require users to add the
flag manually or this package to expose a link() function. I assume
most Windows users would be building and running locally, so let's just
use dynamic linkage on Windows.

While we're here, have benchmark_main link benchmark instead of
re-adding header directories.